package com.suda.jzapp.dao.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACCOUNT".
 */
@Entity
public class Account {

    @Id(autoincrement = true)
    private Long id;
    private Long AccountID;
    private Integer AccountTypeID;
    private String AccountName;
    private Double AccountMoney;
    private String AccountRemark;
    private String AccountColor;
    private Boolean SyncStatus;
    private Boolean isDel;
    private String ObjectID;
    private Integer Index;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    @Generated(hash = 882125521)
    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, Long AccountID, Integer AccountTypeID, String AccountName, Double AccountMoney, String AccountRemark, String AccountColor, Boolean SyncStatus, Boolean isDel, String ObjectID, Integer Index) {
        this.id = id;
        this.AccountID = AccountID;
        this.AccountTypeID = AccountTypeID;
        this.AccountName = AccountName;
        this.AccountMoney = AccountMoney;
        this.AccountRemark = AccountRemark;
        this.AccountColor = AccountColor;
        this.SyncStatus = SyncStatus;
        this.isDel = isDel;
        this.ObjectID = ObjectID;
        this.Index = Index;
    }

    @Generated(hash = 112388405)
    public Account(Long id, Long AccountID, Integer AccountTypeID, String AccountName, Double AccountMoney, String AccountRemark, String AccountColor, Boolean SyncStatus, Boolean isDel, String ObjectID, Integer Index, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.AccountID = AccountID;
        this.AccountTypeID = AccountTypeID;
        this.AccountName = AccountName;
        this.AccountMoney = AccountMoney;
        this.AccountRemark = AccountRemark;
        this.AccountColor = AccountColor;
        this.SyncStatus = SyncStatus;
        this.isDel = isDel;
        this.ObjectID = ObjectID;
        this.Index = Index;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountID() {
        return AccountID;
    }

    public void setAccountID(Long AccountID) {
        this.AccountID = AccountID;
    }

    public Integer getAccountTypeID() {
        return AccountTypeID;
    }

    public void setAccountTypeID(Integer AccountTypeID) {
        this.AccountTypeID = AccountTypeID;
    }

    public String getAccountName() {
        return AccountName;
    }

    public void setAccountName(String AccountName) {
        this.AccountName = AccountName;
    }

    public Double getAccountMoney() {
        return AccountMoney;
    }

    public void setAccountMoney(Double AccountMoney) {
        this.AccountMoney = AccountMoney;
    }

    public String getAccountRemark() {
        return AccountRemark;
    }

    public void setAccountRemark(String AccountRemark) {
        this.AccountRemark = AccountRemark;
    }

    public String getAccountColor() {
        return AccountColor;
    }

    public void setAccountColor(String AccountColor) {
        this.AccountColor = AccountColor;
    }

    public Boolean getSyncStatus() {
        return SyncStatus;
    }

    public void setSyncStatus(Boolean SyncStatus) {
        this.SyncStatus = SyncStatus;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    public String getObjectID() {
        return ObjectID;
    }

    public void setObjectID(String ObjectID) {
        this.ObjectID = ObjectID;
    }

    public Integer getIndex() {
        return Index;
    }

    public void setIndex(Integer Index) {
        this.Index = Index;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
