package com.suda.jzapp.dao.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BUDGET".
 */
@Entity
public class Budget {

    @Id(autoincrement = true)
    private Long id;
    private Double budgetMoney;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    @Generated(hash = 1734026453)
    public Budget() {
    }

    public Budget(Long id) {
        this.id = id;
    }

    @Generated(hash = 1343105915)
    public Budget(Long id, Double budgetMoney, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.budgetMoney = budgetMoney;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getBudgetMoney() {
        return budgetMoney;
    }

    public void setBudgetMoney(Double budgetMoney) {
        this.budgetMoney = budgetMoney;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
