package com.suda.jzapp.dao.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONFIG".
 */
@Entity
public class Config {

    @Id(autoincrement = true)
    private Long id;
    private String key;
    private String value;
    private String ObjectID;

    @Generated(hash = 589037648)
    public Config() {
    }

    public Config(Long id) {
        this.id = id;
    }

    @Generated(hash = 1615747358)
    public Config(Long id, String key, String value, String ObjectID) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.ObjectID = ObjectID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getObjectID() {
        return ObjectID;
    }

    public void setObjectID(String ObjectID) {
        this.ObjectID = ObjectID;
    }

}
