package com.suda.jzapp.dao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD".
*/
public class RecordDao extends AbstractDao<Record, Long> {

    public static final String TABLENAME = "RECORD";

    /**
     * Properties of entity Record.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecordId = new Property(1, Long.class, "RecordId", false, "RECORD_ID");
        public final static Property RecordMoney = new Property(2, Double.class, "RecordMoney", false, "RECORD_MONEY");
        public final static Property RecordTypeID = new Property(3, Long.class, "RecordTypeID", false, "RECORD_TYPE_ID");
        public final static Property RecordType = new Property(4, Integer.class, "RecordType", false, "RECORD_TYPE");
        public final static Property AccountID = new Property(5, Long.class, "AccountID", false, "ACCOUNT_ID");
        public final static Property RecordDate = new Property(6, java.util.Date.class, "RecordDate", false, "RECORD_DATE");
        public final static Property Remark = new Property(7, String.class, "Remark", false, "REMARK");
        public final static Property SyncStatus = new Property(8, Boolean.class, "SyncStatus", false, "SYNC_STATUS");
        public final static Property IsDel = new Property(9, Boolean.class, "isDel", false, "IS_DEL");
        public final static Property ObjectID = new Property(10, String.class, "ObjectID", false, "OBJECT_ID");
        public final static Property Year = new Property(11, Integer.class, "year", false, "YEAR");
        public final static Property Month = new Property(12, Integer.class, "month", false, "MONTH");
        public final static Property Day = new Property(13, Integer.class, "day", false, "DAY");
        public final static Property CreatedAt = new Property(14, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(15, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    };


    public RecordDao(DaoConfig config) {
        super(config);
    }
    
    public RecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RECORD_ID\" INTEGER," + // 1: RecordId
                "\"RECORD_MONEY\" REAL," + // 2: RecordMoney
                "\"RECORD_TYPE_ID\" INTEGER," + // 3: RecordTypeID
                "\"RECORD_TYPE\" INTEGER," + // 4: RecordType
                "\"ACCOUNT_ID\" INTEGER," + // 5: AccountID
                "\"RECORD_DATE\" INTEGER," + // 6: RecordDate
                "\"REMARK\" TEXT," + // 7: Remark
                "\"SYNC_STATUS\" INTEGER," + // 8: SyncStatus
                "\"IS_DEL\" INTEGER," + // 9: isDel
                "\"OBJECT_ID\" TEXT," + // 10: ObjectID
                "\"YEAR\" INTEGER," + // 11: year
                "\"MONTH\" INTEGER," + // 12: month
                "\"DAY\" INTEGER," + // 13: day
                "\"CREATED_AT\" INTEGER," + // 14: createdAt
                "\"UPDATED_AT\" INTEGER);"); // 15: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long RecordId = entity.getRecordId();
        if (RecordId != null) {
            stmt.bindLong(2, RecordId);
        }
 
        Double RecordMoney = entity.getRecordMoney();
        if (RecordMoney != null) {
            stmt.bindDouble(3, RecordMoney);
        }
 
        Long RecordTypeID = entity.getRecordTypeID();
        if (RecordTypeID != null) {
            stmt.bindLong(4, RecordTypeID);
        }
 
        Integer RecordType = entity.getRecordType();
        if (RecordType != null) {
            stmt.bindLong(5, RecordType);
        }
 
        Long AccountID = entity.getAccountID();
        if (AccountID != null) {
            stmt.bindLong(6, AccountID);
        }
 
        java.util.Date RecordDate = entity.getRecordDate();
        if (RecordDate != null) {
            stmt.bindLong(7, RecordDate.getTime());
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(8, Remark);
        }
 
        Boolean SyncStatus = entity.getSyncStatus();
        if (SyncStatus != null) {
            stmt.bindLong(9, SyncStatus ? 1L: 0L);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(10, isDel ? 1L: 0L);
        }
 
        String ObjectID = entity.getObjectID();
        if (ObjectID != null) {
            stmt.bindString(11, ObjectID);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(12, year);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(13, month);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(14, day);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(15, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(16, updatedAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Record entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long RecordId = entity.getRecordId();
        if (RecordId != null) {
            stmt.bindLong(2, RecordId);
        }
 
        Double RecordMoney = entity.getRecordMoney();
        if (RecordMoney != null) {
            stmt.bindDouble(3, RecordMoney);
        }
 
        Long RecordTypeID = entity.getRecordTypeID();
        if (RecordTypeID != null) {
            stmt.bindLong(4, RecordTypeID);
        }
 
        Integer RecordType = entity.getRecordType();
        if (RecordType != null) {
            stmt.bindLong(5, RecordType);
        }
 
        Long AccountID = entity.getAccountID();
        if (AccountID != null) {
            stmt.bindLong(6, AccountID);
        }
 
        java.util.Date RecordDate = entity.getRecordDate();
        if (RecordDate != null) {
            stmt.bindLong(7, RecordDate.getTime());
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(8, Remark);
        }
 
        Boolean SyncStatus = entity.getSyncStatus();
        if (SyncStatus != null) {
            stmt.bindLong(9, SyncStatus ? 1L: 0L);
        }
 
        Boolean isDel = entity.getIsDel();
        if (isDel != null) {
            stmt.bindLong(10, isDel ? 1L: 0L);
        }
 
        String ObjectID = entity.getObjectID();
        if (ObjectID != null) {
            stmt.bindString(11, ObjectID);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(12, year);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(13, month);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(14, day);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(15, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(16, updatedAt.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Record readEntity(Cursor cursor, int offset) {
        Record entity = new Record( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // RecordId
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // RecordMoney
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // RecordTypeID
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // RecordType
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // AccountID
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // RecordDate
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Remark
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // SyncStatus
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // isDel
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ObjectID
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // year
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // month
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // day
            cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)), // createdAt
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Record entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecordId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRecordMoney(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setRecordTypeID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setRecordType(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setAccountID(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setRecordDate(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setRemark(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSyncStatus(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setIsDel(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setObjectID(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setYear(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setMonth(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setDay(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setCreatedAt(cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)));
        entity.setUpdatedAt(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Record entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Record entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
