package com.suda.jzapp.dao.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD_TYPE".
 */
@Entity
public class RecordType implements java.io.Serializable {

    @Id
    private Long id;
    private Long RecordTypeID;
    private String RecordDesc;
    private Integer RecordType;
    private Boolean SysType;
    private Integer RecordIcon;
    private Integer Index;
    private Integer SexProp;
    private Integer Occupation;
    private Boolean SyncStatus;
    private Boolean isDel;
    private String ObjectID;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;

    @Generated(hash = 1378675032)
    public RecordType() {
    }

    public RecordType(Long id) {
        this.id = id;
    }

    public RecordType(Long id, Long RecordTypeID, String RecordDesc, Integer RecordType, Boolean SysType, Integer RecordIcon, Integer Index, Integer SexProp, Integer Occupation, Boolean SyncStatus, Boolean isDel, String ObjectID) {
        this.id = id;
        this.RecordTypeID = RecordTypeID;
        this.RecordDesc = RecordDesc;
        this.RecordType = RecordType;
        this.SysType = SysType;
        this.RecordIcon = RecordIcon;
        this.Index = Index;
        this.SexProp = SexProp;
        this.Occupation = Occupation;
        this.SyncStatus = SyncStatus;
        this.isDel = isDel;
        this.ObjectID = ObjectID;
    }

    @Generated(hash = 1028182860)
    public RecordType(Long id, Long RecordTypeID, String RecordDesc, Integer RecordType, Boolean SysType, Integer RecordIcon, Integer Index, Integer SexProp, Integer Occupation, Boolean SyncStatus, Boolean isDel, String ObjectID, java.util.Date createdAt, java.util.Date updatedAt) {
        this.id = id;
        this.RecordTypeID = RecordTypeID;
        this.RecordDesc = RecordDesc;
        this.RecordType = RecordType;
        this.SysType = SysType;
        this.RecordIcon = RecordIcon;
        this.Index = Index;
        this.SexProp = SexProp;
        this.Occupation = Occupation;
        this.SyncStatus = SyncStatus;
        this.isDel = isDel;
        this.ObjectID = ObjectID;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRecordTypeID() {
        return RecordTypeID;
    }

    public void setRecordTypeID(Long RecordTypeID) {
        this.RecordTypeID = RecordTypeID;
    }

    public String getRecordDesc() {
        return RecordDesc;
    }

    public void setRecordDesc(String RecordDesc) {
        this.RecordDesc = RecordDesc;
    }

    public Integer getRecordType() {
        return RecordType;
    }

    public void setRecordType(Integer RecordType) {
        this.RecordType = RecordType;
    }

    public Boolean getSysType() {
        return SysType;
    }

    public void setSysType(Boolean SysType) {
        this.SysType = SysType;
    }

    public Integer getRecordIcon() {
        return RecordIcon;
    }

    public void setRecordIcon(Integer RecordIcon) {
        this.RecordIcon = RecordIcon;
    }

    public Integer getIndex() {
        return Index;
    }

    public void setIndex(Integer Index) {
        this.Index = Index;
    }

    public Integer getSexProp() {
        return SexProp;
    }

    public void setSexProp(Integer SexProp) {
        this.SexProp = SexProp;
    }

    public Integer getOccupation() {
        return Occupation;
    }

    public void setOccupation(Integer Occupation) {
        this.Occupation = Occupation;
    }

    public Boolean getSyncStatus() {
        return SyncStatus;
    }

    public void setSyncStatus(Boolean SyncStatus) {
        this.SyncStatus = SyncStatus;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    public String getObjectID() {
        return ObjectID;
    }

    public void setObjectID(String ObjectID) {
        this.ObjectID = ObjectID;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
