package com.suda.jzapp.dao.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD_TYPE".
 */
public class RecordType {

    private Long id;
    private Long RecordTypeID;
    private String RecordDesc;
    private Integer RecordType;
    private Boolean SysType;
    private Integer RecordIcon;
    private Integer Index;
    private Integer SexProp;
    private Integer Occupation;
    private Boolean SyncStatus;
    private Boolean isDel;

    public RecordType() {
    }

    public RecordType(Long id) {
        this.id = id;
    }

    public RecordType(Long id, Long RecordTypeID, String RecordDesc, Integer RecordType, Boolean SysType, Integer RecordIcon, Integer Index, Integer SexProp, Integer Occupation, Boolean SyncStatus, Boolean isDel) {
        this.id = id;
        this.RecordTypeID = RecordTypeID;
        this.RecordDesc = RecordDesc;
        this.RecordType = RecordType;
        this.SysType = SysType;
        this.RecordIcon = RecordIcon;
        this.Index = Index;
        this.SexProp = SexProp;
        this.Occupation = Occupation;
        this.SyncStatus = SyncStatus;
        this.isDel = isDel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRecordTypeID() {
        return RecordTypeID;
    }

    public void setRecordTypeID(Long RecordTypeID) {
        this.RecordTypeID = RecordTypeID;
    }

    public String getRecordDesc() {
        return RecordDesc;
    }

    public void setRecordDesc(String RecordDesc) {
        this.RecordDesc = RecordDesc;
    }

    public Integer getRecordType() {
        return RecordType;
    }

    public void setRecordType(Integer RecordType) {
        this.RecordType = RecordType;
    }

    public Boolean getSysType() {
        return SysType;
    }

    public void setSysType(Boolean SysType) {
        this.SysType = SysType;
    }

    public Integer getRecordIcon() {
        return RecordIcon;
    }

    public void setRecordIcon(Integer RecordIcon) {
        this.RecordIcon = RecordIcon;
    }

    public Integer getIndex() {
        return Index;
    }

    public void setIndex(Integer Index) {
        this.Index = Index;
    }

    public Integer getSexProp() {
        return SexProp;
    }

    public void setSexProp(Integer SexProp) {
        this.SexProp = SexProp;
    }

    public Integer getOccupation() {
        return Occupation;
    }

    public void setOccupation(Integer Occupation) {
        this.Occupation = Occupation;
    }

    public Boolean getSyncStatus() {
        return SyncStatus;
    }

    public void setSyncStatus(Boolean SyncStatus) {
        this.SyncStatus = SyncStatus;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

}
